
version: 2

updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Kolkata"

    groups:
      github-actions:
        patterns:
          - "*"

  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Kolkata"

    groups:
      npm-dependencies:
        patterns:
          - "*"
